-- ============================================================
-- 012: risk_scores table for ML scoring pipeline output
-- ============================================================

CREATE TABLE IF NOT EXISTS public.risk_scores (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_code    text NOT NULL UNIQUE,
  score        numeric(5,1) NOT NULL CHECK (score BETWEEN 0 AND 100),
  risk_level   text NOT NULL CHECK (risk_level IN ('low','medium','high','critical')),
  factors_json jsonb,
  computed_at  date NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX IF NOT EXISTS idx_risk_scores_level ON public.risk_scores(risk_level);
CREATE INDEX IF NOT EXISTS idx_risk_scores_date  ON public.risk_scores(computed_at);

ALTER TABLE public.risk_scores ENABLE ROW LEVEL SECURITY;

-- Public read — dashboard shows risk scores to all authenticated users
CREATE POLICY "risk_scores: read"
  ON public.risk_scores FOR SELECT
  USING (true);

-- Only service role / admin can write (scoring job uses service key)
CREATE POLICY "risk_scores: admin write"
  ON public.risk_scores FOR ALL
  USING (public.get_my_role() = 'admin');

GRANT SELECT ON public.risk_scores TO authenticated, anon;
GRANT INSERT, UPDATE ON public.risk_scores TO authenticated;
